### ISSUE TITLE
Enabling Travis-CI

### ISSUE THREAD

**Issue by lassebunk** [jtzemp/base62#10]
Hi @jtzemp,

I have prepared the project for Travis-CI to enable automated testing of the supported Ruby versions and new incoming pull requests.

Could you go to https://travis-ci.org/profile/jtzemp and flick the On switch for the project. This enables hooks for Travis-CI when we push to the GitHub repo.

Thanks.

**Comment by jtzemp** [comment]
I enabled travis in my account. Thanks for setting that up!

**Comment by lassebunk** [comment]
Thanks! That should be okay then :)
